name: No Cache
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Execute No cache
        run: python nocache.py
      - name: Push Repo
        run: |
          git config user.name github_actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Nocache Exec"
          git push
